version: '3.7'

services:
  vue-app:
    build:
      context: .  # Use the current directory for the build context
      dockerfile: Dockerfile  # The Dockerfile we just created
    container_name: vue-app
    networks:
      - my-network
    expose:
      - "80"  # Expose the internal port 80 to Traefik
    labels:
      - "traefik.enable=true"  # Enable Traefik on this service
      - "traefik.http.routers.vue-app.rule=Host(`uzora.uz`)"  # Domain for routing
      - "traefik.http.routers.vue-app.entrypoints=web,websecure"  # Enable both HTTP and HTTPS
      - "traefik.http.services.vue-app.loadbalancer.server.port=80"  # Server port inside the container
      - "traefik.http.routers.vue-app.tls.certresolver=myresolver"  # Use Let's Encrypt for SSL
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"  # Define redirect middleware
      - "traefik.http.routers.vue-app.middlewares=redirect-to-https"  # Apply middleware for HTTP to HTTPS redirection

#  traefik-vue: already exists traefik
#    image: traefik:v2.8
#    container_name: traefik-vue
#    command:
#      - "--api.insecure=true"  # Enable the dashboard (insecure for local dev)
#      - "--providers.docker=true"  # Enable Docker provider
#      - "--entrypoints.web.address=:80"  # HTTP entrypoint
#      - "--entrypoints.websecure.address=:443"  # HTTPS entrypoint
#      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"  # HTTP challenge for Let's Encrypt
#      - "--certificatesresolvers.myresolver.acme.email=shaxa882@gmail.com"  # Replace with your email
#      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json"  # ACME storage for certificates
#    ports:
#      - "8081:80"   # Expose HTTP port (internal port 8080 -> external 80)
#      - "8443:443"   # Expose HTTPS port (internal port 443 -> external 443)
#      - "8181:8080"  # Dashboard for the second instance
#    volumes:
#      - "./traefik/acme.json:/etc/traefik/acme.json"  # Persistent storage for certificates
#      - "/var/run/docker.sock:/var/run/docker.sock"  # Mount Docker socket to allow Traefik to access Docker API
#    networks:
#      - web
#    labels:
#      - "traefik.enable=true"  # Enable Traefik for this service

networks:
  my-network:
    external: true

volumes:
  traefik:
    external: false
