name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          # Save the SSH private key to a temporary file
          touch vps_key.pem
          chmod 600 vps_key.pem
          echo "$VPS_SSH_KEY" > vps_key.pem
          
          # Run the deployment script on the remote VPS
          ssh -i vps_key.pem -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP 'bash -s' <  ./deploy.sh
          
          # Remove the key file after use
          rm vps_key.pem